// lib/mock-data.ts
import type { Job, Company, JobSource, PricingPlan } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: 'j1', title: 'Senior Frontend Engineer', company: 'Vercel', logo: 'V',
    category: 'engineering', type: 'full-time', level: 'senior',
    salaryMin: 130000, salaryMax: 180000, currency: 'USD',
    location: 'Worldwide', timezone: 'Any', remote: true,
    description: `We're looking for a Senior Frontend Engineer to help build the next generation of Stripe's payment interfaces. You'll work on the Dashboard used by millions of businesses globally, building fast, accessible, and beautiful UIs.\n\nYou'll collaborate closely with product managers, designers, and backend engineers to deliver features that matter to our users.`,
    requirements: ['5+ years React/TypeScript', 'Performance optimization expert', 'Accessibility (WCAG 2.1)', 'Testing culture (Playwright, Jest)'],
    skills: ['React', 'TypeScript', 'CSS', 'GraphQL', 'Testing'],
    benefits: ['Competitive equity', 'Remote stipend $1,000/yr', 'Health insurance', 'L&D budget $2,000/yr'],
    applyUrl: 'https://vercel.com/careers/senior-frontend', applyEmail: 'jobs@vercel.com',
    posted: new Date(Date.now() - 1*86400000).toISOString(), featured: true, isNew: true, source: 'rss',
  },
  {
    id: 'j2', title: 'Product Designer', company: 'Notion', logo: 'N',
    category: 'design', type: 'full-time', level: 'mid',
    salaryMin: 100000, salaryMax: 140000, currency: 'USD',
    location: 'US / Europe', timezone: 'EST/CET', remote: true,
    description: `Design features for Notion's 30M+ users. You'll own end-to-end design for new product areas — from early research and ideation through to shipping and iteration.\n\nWe're a small design team with enormous impact. You'll work on problems that affect millions of knowledge workers worldwide.`,
    requirements: ['4+ years product design', 'Figma expert', 'Design systems experience', 'User research skills'],
    skills: ['Figma', 'Design Systems', 'Prototyping', 'User Research', 'Motion'],
    applyUrl: 'https://notion.so/jobs/product-designer', applyEmail: 'design@notion.so',
    posted: new Date(Date.now() - 2*86400000).toISOString(), featured: false, isNew: true, source: 'rss',
  },
  {
    id: 'j3', title: 'Backend Engineer – Go', company: 'Cloudflare', logo: 'C',
    category: 'engineering', type: 'full-time', level: 'senior',
    salaryMin: 140000, salaryMax: 200000, currency: 'USD',
    location: 'Worldwide', timezone: 'Any', remote: true,
    description: `Work on Cloudflare Workers, the edge computing platform running on 300+ global data centers. You'll build the runtime that powers millions of serverless applications worldwide.`,
    requirements: ['Go or Rust expertise', 'Distributed systems', 'Network programming', 'Linux internals'],
    skills: ['Go', 'Rust', 'Distributed Systems', 'Networking', 'Linux'],
    applyUrl: 'https://cloudflare.com/careers/go-engineer',
    posted: new Date(Date.now() - 3*86400000).toISOString(), featured: true, isNew: false, source: 'scrape',
  },
  {
    id: 'j4', title: 'Growth Marketing Manager', company: 'Linear', logo: 'L',
    category: 'marketing', type: 'full-time', level: 'mid',
    salaryMin: 90000, salaryMax: 130000, currency: 'USD',
    location: 'Worldwide', timezone: 'Any', remote: true,
    description: `Drive growth for the project management tool developers love. Own SEO, content strategy, and paid acquisition to help Linear reach the next million users.`,
    requirements: ['3+ years growth marketing', 'B2B SaaS experience', 'Data-driven approach', 'Strong writer'],
    skills: ['SEO', 'Content Marketing', 'Analytics', 'Paid Acquisition', 'HubSpot'],
    applyUrl: 'https://linear.app/jobs', applyEmail: 'growth@linear.app',
    posted: new Date(Date.now() - 4*86400000).toISOString(), featured: false, isNew: false, source: 'manual',
  },
  {
    id: 'j5', title: 'Data Scientist – NLP', company: 'Hugging Face', logo: 'H',
    category: 'data', type: 'full-time', level: 'senior',
    salaryMin: 120000, salaryMax: 170000, currency: 'USD',
    location: 'Europe / US', timezone: 'CET/EST', remote: true,
    description: `Advance the state of open-source AI at the world's leading AI platform. Work on model evaluation, benchmark datasets, and applied NLP research that helps the community.`,
    requirements: ['ML/AI background', 'Python & PyTorch', 'NLP research experience', 'Open source contributor'],
    skills: ['Python', 'PyTorch', 'Statistics', 'NLP', 'Transformers'],
    applyUrl: 'https://huggingface.co/jobs',
    posted: new Date(Date.now() - 5*86400000).toISOString(), featured: false, isNew: false, source: 'rss',
  },
  {
    id: 'j6', title: 'Developer Advocate', company: 'Vercel', logo: 'V',
    category: 'engineering', type: 'full-time', level: 'mid',
    salaryMin: 110000, salaryMax: 160000, currency: 'USD',
    location: 'Worldwide', timezone: 'Any', remote: true,
    description: `Help developers build faster web applications with Next.js and Vercel. Create demos, write documentation, speak at conferences, and contribute to open source.`,
    requirements: ['Developer advocacy experience', 'Strong communication', 'Next.js & React knowledge', 'Content creator'],
    skills: ['Next.js', 'React', 'Technical Writing', 'Public Speaking', 'Open Source'],
    applyUrl: 'https://vercel.com/careers',
    posted: new Date(Date.now() - 6*86400000).toISOString(), featured: false, isNew: false, source: 'rss',
  },
  {
    id: 'j7', title: 'Finance Manager – Remote', company: 'Deel', logo: 'D',
    category: 'finance', type: 'full-time', level: 'senior',
    salaryMin: 100000, salaryMax: 150000, currency: 'USD',
    location: 'Worldwide', timezone: 'Any', remote: true,
    description: `Manage financial operations for the global payroll & compliance platform trusted by 35,000+ companies. Own FP&A, reporting, and multi-jurisdictional compliance.`,
    requirements: ['CPA or CFA equivalent', '5+ years finance', 'International experience', 'SaaS metrics'],
    skills: ['Financial Modeling', 'Excel', 'FP&A', 'GAAP', 'IFRS'],
    applyUrl: 'https://deel.com/careers',
    posted: new Date(Date.now() - 7*86400000).toISOString(), featured: false, isNew: false, source: 'rss',
  },
  {
    id: 'j8', title: 'iOS Engineer', company: 'Spotify', logo: 'S',
    category: 'engineering', type: 'full-time', level: 'senior',
    salaryMin: 125000, salaryMax: 175000, currency: 'USD',
    location: 'Europe', timezone: 'CET', remote: true,
    description: `Build the iOS app used by 600M+ music lovers worldwide. You'll own features from design collaboration all the way to production, working on a high-traffic, high-scale mobile product.`,
    requirements: ['Swift expert', '5+ years iOS', 'Performance optimization', 'CI/CD experience'],
    skills: ['Swift', 'SwiftUI', 'iOS SDK', 'Instruments', 'CI/CD'],
    applyUrl: 'https://spotify.com/careers',
    posted: new Date(Date.now() - 8*86400000).toISOString(), featured: false, isNew: false, source: 'rss',
  },
  {
    id: 'j9', title: 'Customer Success Manager', company: 'Loom', logo: 'L',
    category: 'sales', type: 'full-time', level: 'mid',
    salaryMin: 75000, salaryMax: 110000, currency: 'USD',
    location: 'US Remote', timezone: 'PST/CST/EST', remote: true,
    description: `Help enterprise customers unlock value from async video communication. Own renewals, expansion opportunities, and the full customer onboarding journey.`,
    requirements: ['3+ years CSM', 'B2B SaaS', 'Strong communicator', 'Salesforce proficiency'],
    skills: ['Customer Success', 'Salesforce', 'Communication', 'Analytics', 'QBRs'],
    applyUrl: 'https://loom.com/jobs',
    posted: new Date(Date.now() - 9*86400000).toISOString(), featured: false, isNew: false, source: 'scrape',
  },
  {
    id: 'j10', title: 'ML Infrastructure Engineer', company: 'Anthropic', logo: 'A',
    category: 'engineering', type: 'full-time', level: 'senior',
    salaryMin: 180000, salaryMax: 250000, currency: 'USD',
    location: 'US Remote', timezone: 'PST/EST', remote: true,
    description: `Build the infrastructure that powers large language model training and inference at scale. You'll work on distributed training systems, model serving infrastructure, and developer tooling.`,
    requirements: ['Distributed systems expertise', 'Python & C++', 'ML frameworks (PyTorch)', 'CUDA experience a plus'],
    skills: ['Python', 'CUDA', 'Kubernetes', 'PyTorch', 'Distributed Systems'],
    applyUrl: 'https://anthropic.com/careers',
    posted: new Date(Date.now() - 10*86400000).toISOString(), featured: true, isNew: false, source: 'manual',
  },
  {
    id: 'j11', title: 'UX Researcher', company: 'Figma', logo: 'F',
    category: 'design', type: 'full-time', level: 'mid',
    salaryMin: 105000, salaryMax: 150000, currency: 'USD',
    location: 'US / Canada', timezone: 'Any', remote: true,
    description: `Lead user research for the design tool used by 8M+ designers. Run mixed-methods studies, synthesize insights, and directly influence the product roadmap.`,
    requirements: ['4+ years UX research', 'Mixed methods', 'Research synthesis', 'Cross-functional collaboration'],
    skills: ['User Research', 'Figma', 'Surveys', 'Usability Testing', 'Data Analysis'],
    applyUrl: 'https://figma.com/careers',
    posted: new Date(Date.now() - 11*86400000).toISOString(), featured: false, isNew: false, source: 'manual',
  },
  {
    id: 'j12', title: 'HR Business Partner', company: 'GitLab', logo: 'G',
    category: 'hr', type: 'full-time', level: 'mid',
    salaryMin: 85000, salaryMax: 120000, currency: 'USD',
    location: 'Worldwide', timezone: 'Any', remote: true,
    description: `Support GitLab's fully remote team of 2,000+ across the full employee lifecycle. GitLab literally wrote the book on remote work — join the team that pioneered it.`,
    requirements: ['5+ years HRBP', 'Remote-first experience', 'Organizational development', 'International HR'],
    skills: ['HR Strategy', 'Employee Relations', 'Compensation', 'Compliance', 'Culture'],
    applyUrl: 'https://gitlab.com/careers',
    posted: new Date(Date.now() - 12*86400000).toISOString(), featured: false, isNew: false, source: 'rss',
  },
];

export const MOCK_COMPANIES: Company[] = [
  { id:'c1', name:'Stripe', countryCode:'US', country:'United States', logo:'S', jobCount:12, categories:['engineering','finance','design'], size:'1000+', website:'https://stripe.com', featured:true },
  { id:'c2', name:'Notion', countryCode:'US', country:'United States', logo:'N', jobCount:8, categories:['engineering','design','marketing'], size:'200-500' },
  { id:'c3', name:'Cloudflare', countryCode:'US', country:'United States', logo:'C', jobCount:20, categories:['engineering'], size:'1000+', featured:true },
  { id:'c4', name:'GitLab', countryCode:'US', country:'United States', logo:'G', jobCount:35, categories:['engineering','hr','sales'], size:'1000+', featured:true },
  { id:'c5', name:'Shopify', countryCode:'CA', country:'Canada', logo:'S', jobCount:22, categories:['engineering','design','marketing'], size:'1000+' },
  { id:'c6', name:'Automattic', countryCode:'US', country:'United States', logo:'A', jobCount:15, categories:['engineering','marketing'], size:'1000+' },
  { id:'c7', name:'Figma', countryCode:'US', country:'United States', logo:'F', jobCount:10, categories:['engineering','design'], size:'500-1000' },
  { id:'c8', name:'Linear', countryCode:'US', country:'United States', logo:'L', jobCount:6, categories:['engineering','design'], size:'50-200' },
  { id:'c9', name:'Vercel', countryCode:'US', country:'United States', logo:'V', jobCount:14, categories:['engineering','marketing'], size:'200-500' },
  { id:'c10', name:'Spotify', countryCode:'SE', country:'Sweden', logo:'S', jobCount:18, categories:['engineering','design','marketing'], size:'1000+' },
  { id:'c11', name:'Deel', countryCode:'US', country:'United States', logo:'D', jobCount:25, categories:['engineering','finance','hr','sales'], size:'1000+' },
  { id:'c12', name:'Basecamp', countryCode:'US', country:'United States', logo:'B', jobCount:5, categories:['engineering','design'], size:'50-200' },
  { id:'c13', name:'Buffer', countryCode:'US', country:'United States', logo:'B', jobCount:4, categories:['engineering','marketing'], size:'50-200' },
  { id:'c14', name:'Zapier', countryCode:'US', country:'United States', logo:'Z', jobCount:11, categories:['engineering','marketing','sales'], size:'500-1000' },
  { id:'c15', name:'InVision', countryCode:'US', country:'United States', logo:'I', jobCount:7, categories:['design','engineering'], size:'200-500' },
  { id:'c16', name:'Doist', countryCode:'PT', country:'Portugal', logo:'D', jobCount:3, categories:['engineering','design'], size:'50-200' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    nairaPrice: 0,
    billing: 'daily',
    description: "Browse jobs and explore what's available.",
    cta: 'Start Free',
    features: [
      { text: 'Browse all remote jobs', included: true },
      { text: 'Basic search & filters', included: true },
      { text: 'Save up to 5 jobs', included: true },
      { text: 'Company profiles', included: true },
      { text: 'Apply links & contact emails', included: false },
      { text: 'CV upload & auto-apply', included: false },
      { text: 'Application tracker', included: false },
      { text: 'Job alerts', included: false },
    ],
  },
  {
    id: 'daily',
    name: 'Day Pass',
    nairaPrice: 1000,
    billing: 'daily',
    description: 'Full access for 24 hours. Perfect for active job hunting.',
    cta: 'Get Day Pass',
    badge: '24hrs',
    features: [
      { text: 'Everything in Free', included: true },
      { text: 'Unlock all apply links & emails', included: true },
      { text: 'CV upload & auto-apply', included: true },
      { text: 'Full application tracker', included: true },
      { text: 'Job alerts for 24 hrs', included: true },
      { text: 'Priority support', included: false },
      { text: 'Renews automatically', included: false },
      { text: 'Job alerts (ongoing)', included: false },
    ],
  },
  {
    id: 'pro',
    name: 'Pro Monthly',
    nairaPrice: 8999,
    billing: 'monthly',
    description: 'Everything you need to land your remote job.',
    cta: 'Get Pro',
    popular: true,
    features: [
      { text: 'Everything in Free', included: true },
      { text: 'Unlock all apply links & emails', included: true },
      { text: 'CV upload & auto-apply', included: true },
      { text: 'Full application tracker', included: true },
      { text: 'Ongoing job alerts', included: true },
      { text: 'Priority support', included: true },
      { text: 'Cancel anytime', included: true },
      { text: 'Renews monthly automatically', included: true },
    ],
  },
  {
    id: 'pro_annual',
    name: 'Pro Annual',
    nairaPrice: 89999,
    nairaMonthlyEquiv: 7500,
    billing: 'annually',
    description: 'Best value — save ₦17,989 vs monthly.',
    cta: 'Get Annual',
    badge: 'Best Value',
    features: [
      { text: 'Everything in Pro Monthly', included: true },
      { text: 'Save ₦17,989 per year', included: true },
      { text: 'Priority support', included: true },
      { text: 'Early access to new features', included: true },
      { text: 'Cancel anytime', included: true },
      { text: 'Renews annually', included: true },
      { text: 'Dedicated account manager', included: false },
      { text: 'API access', included: false },
    ],
  },
];

export const EMBEDDED_RSS_COMPANIES: Array<{name:string; country:string; rssUrl:string; category:string}> = [
  { name:'We Work Remotely', country:'US', rssUrl:'https://weworkremotely.com/remote-jobs.rss', category:'All' },
  { name:'Remote OK', country:'US', rssUrl:'https://remoteok.com/remote-jobs.rss', category:'All' },
  { name:'Remotive', country:'EU', rssUrl:'https://remotive.com/remote-jobs/feed/json', category:'All' },
  { name:'Working Nomads', country:'EU', rssUrl:'https://www.workingnomads.com/feed', category:'All' },
  { name:'GitHub Jobs', country:'US', rssUrl:'https://jobs.github.com/positions.json?utf8=✓&description=remote', category:'Engineering' },
  { name:'Dribbble Jobs', country:'US', rssUrl:'https://dribbble.com/jobs.rss?location=anywhere', category:'Design' },
  { name:'HN Who is Hiring', country:'US', rssUrl:'https://hnhiring.com/feed.xml', category:'Engineering' },
  { name:'Europe Remotely', country:'EU', rssUrl:'https://europeremotely.com/feed.xml', category:'All' },
  { name:'Remote.co', country:'US', rssUrl:'https://remote.co/remote-jobs/feed/', category:'All' },
  { name:'JustRemote', country:'EU', rssUrl:'https://justremote.co/feed.xml', category:'All' },
];
