// lib/vc-boards.ts — Complete VC job board registry with platform detection + ingestion strategies
// Covers all 40+ VC boards from the user's list

export type Platform =
  | 'getro'
  | 'yc'
  | 'custom'
  | 'workable'
  | 'greenhouse'
  | 'lever'
  | 'ashby'
  | 'js-spa'

export type IngestionStatus =
  | 'free-api'    // Free public API — works out of the box
  | 'key-needed'  // API exists but needs key
  | 'js-only'     // No API — JS-rendered, would need headless browser
  | 'rss';        // RSS feed available

export interface VCBoard {
  id: string;
  name: string;
  url: string;
  logo?: string;
  hq: string;
  platform: Platform;
  ingestionStatus: IngestionStatus;
  apiEndpoint?: string;        // direct API URL if available
  rssUrl?: string;
  notes?: string;
  approxJobs?: number;
  focus?: string;              // e.g. "US/Global", "Europe", "Early Stage"
}

export const VC_BOARDS: VCBoard[] = [
  // ── FREE API / YC ──────────────────────────────────────────────────────
  {
    id: 'yc',
    name: 'Y Combinator — Work at a Startup',
    url: 'https://www.workatastartup.com',
    logo: 'https://www.ycombinator.com/favicon.ico',
    hq: 'San Francisco, USA',
    platform: 'yc',
    ingestionStatus: 'free-api',
    apiEndpoint: 'https://yc-oss.github.io/api/companies/hiring.json',
    notes: 'Free public API via yc-oss community project. Returns 1400+ hiring companies with Greenhouse/Lever links. No key needed.',
    approxJobs: 15000,
    focus: 'Global / All Stages',
  },

  {
    id: 'sequoia',
    name: 'Sequoia Capital',
    url: 'https://www.sequoiacap.com/jobs',
    hq: 'Menlo Park, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 2000,
    focus: 'Global / Growth',
  },
  {
    id: 'a16z',
    name: 'Andreessen Horowitz (a16z)',
    url: 'https://a16z.com/jobs',
    hq: 'Menlo Park, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    notes: 'JS-rendered platform. Add individual Greenhouse/Lever URLs from portfolio companies.',
    approxJobs: 3000,
    focus: 'Global / All Stages',
  },
  {
    id: 'khosla',
    name: 'Khosla Ventures',
    url: 'https://www.khoslaventures.com/careers',
    hq: 'Menlo Park, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    notes: 'JS-rendered platform. Add individual Greenhouse/Lever URLs from portfolio companies.',
    approxJobs: 800,
    focus: 'Deep Tech / US',
  },
  {
    id: 'generalcatalyst',
    name: 'General Catalyst',
    url: 'https://www.generalcatalyst.com/jobs',
    hq: 'Cambridge, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 1200,
    focus: 'Global / Growth',
  },
  {
    id: 'foundersfund',
    name: "Founders Fund",
    url: 'https://www.foundersfund.com/jobs',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 600,
    focus: 'Deep Tech / US',
  },
  {
    id: 'greylock',
    name: 'Greylock',
    url: 'https://greylock.com/jobs/',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 900,
    focus: 'Enterprise / US',
  },
  {
    id: 'firstround',
    name: 'First Round Capital',
    url: 'https://www.firstround.com/jobs',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 700,
    focus: 'Early Stage / US',
  },
  {
    id: 'bvp',
    name: 'Bessemer Venture Partners',
    url: 'https://www.bvp.com/portfolio/jobs',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 1000,
    focus: 'Global / Growth',
  },
  {
    id: 'sparkvc',
    name: 'Spark Capital',
    url: 'https://www.sparkcapital.com/jobs',
    hq: 'Boston, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 500,
    focus: 'US / Consumer',
  },
  {
    id: 'matrix',
    name: 'Matrix Partners',
    url: 'https://www.matrixpartners.com/jobs',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 400,
    focus: 'US / Enterprise',
  },
  {
    id: 'baincv',
    name: 'Bain Capital Ventures',
    url: 'https://www.baincapitalventures.com/careers/',
    hq: 'Boston, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 500,
    focus: 'US / Fintech',
  },
  {
    id: 'redpoint',
    name: 'Redpoint Ventures',
    url: 'https://www.redpoint.com/jobs',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 400,
    focus: 'US / Enterprise',
  },
  {
    id: 'menlovc',
    name: 'Menlo Ventures',
    url: 'https://www.menlovc.com/jobs',
    hq: 'Menlo Park, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 300,
    focus: 'US / AI & Enterprise',
  },
  {
    id: 'crv',
    name: 'CRV',
    url: 'https://www.crv.com/jobs',
    hq: 'Cambridge, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 350,
    focus: 'US / Early Stage',
  },
  {
    id: 'scalevp',
    name: 'Scale Venture Partners',
    url: 'https://www.scalevp.com/jobs',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 300,
    focus: 'US / SaaS',
  },
  {
    id: 'ivp',
    name: 'IVP',
    url: 'https://www.ivp.com/portfolio-jobs/',
    hq: 'San Francisco, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 400,
    focus: 'US / Growth',
  },
  {
    id: 'battery',
    name: 'Battery Ventures',
    url: 'https://www.battery.com/jobs/',
    hq: 'Boston, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 500,
    focus: 'US / Enterprise',
  },
  {
    id: 'lsvp',
    name: 'Lightspeed Venture Partners',
    url: 'https://lsvp.com/careers/',
    hq: 'Menlo Park, USA',
    platform: 'js-spa',
    ingestionStatus: 'key-needed',
    approxJobs: 1000,
    focus: 'Global / Growth',
  },

  // ── GETRO PLATFORM (JS SPA, paid API) ──────────────────────────────────
  {
    id: 'hvcapital',
    name: 'HV Capital',
    url: 'https://hv.getro.com/',
    hq: 'Munich, Germany',
    platform: 'getro',
    ingestionStatus: 'js-only',
    notes: 'Getro platform. Paid API required. 117 companies, ~2000+ jobs.',
    approxJobs: 2000,
    focus: 'Europe / Growth',
  },
  {
    id: 'insightpartners',
    name: 'Insight Partners',
    url: 'https://jobs.insightpartners.com/jobs',
    hq: 'New York, USA',
    platform: 'getro',
    ingestionStatus: 'js-only',
    notes: 'Getro platform.',
    approxJobs: 3000,
    focus: 'Global / Growth',
  },
  {
    id: 'antler',
    name: 'Antler',
    url: 'https://www.antler.co/jobs',
    hq: 'Singapore',
    platform: 'getro',
    ingestionStatus: 'js-only',
    notes: 'Getro platform (careers.antler.co). Global pre-seed fund.',
    approxJobs: 1500,
    focus: 'Global / Pre-seed',
  },
  {
    id: 'atomico',
    name: 'Atomico',
    url: 'https://www.atomico.com/jobs',
    hq: 'London, UK',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 800,
    focus: 'Europe / Growth',
  },
  {
    id: 'seedcamp',
    name: 'Seedcamp',
    url: 'https://seedcamp.com/jobs/',
    hq: 'London, UK',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 600,
    focus: 'Europe / Pre-seed',
  },
  {
    id: 'northzone',
    name: 'Northzone',
    url: 'https://northzone.com/jobs/',
    hq: 'Stockholm, Sweden',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 500,
    focus: 'Europe / Growth',
  },
  {
    id: 'speedinvest',
    name: 'Speedinvest',
    url: 'https://www.speedinvest.com/jobs',
    hq: 'Vienna, Austria',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 400,
    focus: 'Europe / Early Stage',
  },
  {
    id: 'eqtventures',
    name: 'EQT Ventures',
    url: 'https://eqtventures.com/jobs/',
    hq: 'Stockholm, Sweden',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 700,
    focus: 'Europe / Growth',
  },
  {
    id: 'lakestar',
    name: 'Lakestar',
    url: 'https://www.lakestar.com/careers',
    hq: 'Zurich, Switzerland',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 300,
    focus: 'Europe / Growth',
  },
  {
    id: 'creandum',
    name: 'Creandum',
    url: 'https://www.creandum.com/jobs',
    hq: 'Stockholm, Sweden',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 300,
    focus: 'Europe / Early Stage',
  },
  {
    id: 'partech',
    name: 'Partech Partners',
    url: 'https://partechpartners.com/jobs',
    hq: 'Paris, France',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 400,
    focus: 'Europe & Africa',
  },
  {
    id: 'earlybird',
    name: 'Earlybird VC',
    url: 'https://earlybird.com/jobs/',
    hq: 'Berlin, Germany',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 400,
    focus: 'Europe / Early Stage',
  },
  {
    id: 'dawncapital',
    name: 'Dawn Capital',
    url: 'https://dawncapital.com/jobs/',
    hq: 'London, UK',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 300,
    focus: 'Europe / B2B SaaS',
  },
  {
    id: 'mangrove',
    name: 'Mangrove Capital',
    url: 'https://www.mangrove.vc/jobs',
    hq: 'Luxembourg',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 200,
    focus: 'Europe / Early Stage',
  },
  {
    id: 'cherryvc',
    name: 'Cherry Ventures',
    url: 'https://www.cherry.vc/jobs',
    hq: 'Berlin, Germany',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 300,
    focus: 'Europe / Early Stage',
  },
  {
    id: 'pointnine',
    name: 'Point Nine Capital',
    url: 'https://www.pointnine.com/jobs',
    hq: 'Berlin, Germany',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 200,
    focus: 'Europe / SaaS',
  },
  {
    id: 'projecta',
    name: 'Project A Ventures',
    url: 'https://www.project-a.com/careers',
    hq: 'Berlin, Germany',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 300,
    focus: 'Europe / Operational VC',
  },
  {
    id: 'alven',
    name: 'Alven Capital',
    url: 'https://alven.co/jobs/',
    hq: 'Paris, France',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 200,
    focus: 'France / Early Stage',
  },
  {
    id: 'balderton',
    name: 'Balderton Capital',
    url: 'https://www.balderton.com/jobs/',
    hq: 'London, UK',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 500,
    focus: 'Europe / Growth',
  },
  {
    id: 'phoenixcourt',
    name: 'Phoenix Court',
    url: 'https://www.phoenixcourt.fo/jobs',
    hq: 'Faroe Islands',
    platform: 'getro',
    ingestionStatus: 'js-only',
    approxJobs: 100,
    focus: 'Nordic',
  },

  // ── CUSTOM / HAS SOME API ───────────────────────────────────────────────
  {
    id: 'indexventures',
    name: 'Index Ventures',
    url: 'https://www.indexventures.com/startup-jobs',
    hq: 'London / San Francisco',
    platform: 'custom',
    ingestionStatus: 'js-only',
    notes: 'Custom Django/Elasticsearch app. JS-rendered. 9,800+ jobs across portfolio. No public API.',
    approxJobs: 9800,
    focus: 'Global / Growth',
  },
];

// Platform metadata for UI display
export const PLATFORM_META: Record<Platform, { label: string; color: string; apiAvailable: boolean; apiNote: string }> = {
  getro:      { label: 'Getro',      color: 'text-violet-700 bg-violet-50 dark:text-violet-400 dark:bg-violet-900/20', apiAvailable: false, apiNote: 'JS-rendered, paid API' },
  yc:         { label: 'YC Public API',   color: 'text-orange-700 bg-orange-50 dark:text-orange-400 dark:bg-orange-900/20',   apiAvailable: true,  apiNote: 'Free — no key needed (yc-oss.github.io)' },
  greenhouse: { label: 'Greenhouse ATS',  color: 'text-green-700 bg-green-50 dark:text-green-400 dark:bg-green-900/20',       apiAvailable: true,  apiNote: 'Free public JSON API per company board' },
  lever:      { label: 'Lever ATS',       color: 'text-green-700 bg-green-50 dark:text-green-400 dark:bg-green-900/20',       apiAvailable: true,  apiNote: 'Free public JSON API per company' },
  ashby:      { label: 'Ashby ATS',       color: 'text-green-700 bg-green-50 dark:text-green-400 dark:bg-green-900/20',       apiAvailable: true,  apiNote: 'Free public JSON API per company' },
  workable:   { label: 'Workable ATS',    color: 'text-cyan-700 bg-cyan-50 dark:text-cyan-400 dark:bg-cyan-900/20',           apiAvailable: true,  apiNote: 'Free public JSON API per company' },
  custom:     { label: 'Custom Site',     color: 'text-stone-600 bg-stone-100 dark:text-stone-400 dark:bg-stone-800',         apiAvailable: false, apiNote: 'No public API — JS-rendered' },
  'js-spa':   { label: 'JS SPA',          color: 'text-amber-700 bg-amber-50 dark:text-amber-400 dark:bg-amber-900/20',       apiAvailable: false, apiNote: 'No public API — needs headless browser' },
};

export const INGESTION_STATUS_META = {
  'free-api': { label: '✅ Free API',      color: 'text-green-700 dark:text-green-400' },
  'key-needed': { label: '🔑 Key needed',  color: 'text-purple-700 dark:text-purple-400' },
  'js-only':  { label: '⚡ JS only',       color: 'text-amber-700 dark:text-amber-400' },
  'rss':      { label: '📡 RSS feed',      color: 'text-blue-700 dark:text-blue-400' },
};

// Get total approx job count across all boards
export const TOTAL_APPROX_JOBS = VC_BOARDS.reduce((s, b) => s + (b.approxJobs ?? 0), 0);
